### ISSUE TITLE
switch to connection strings instead of separate connection parameters

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch3#255]
# Pros
- [connection strings](https://www.postgresql.org/docs/15/libpq-connect.html#LIBPQ-CONNSTRING) are flexible and long time supported
- one can use either key-value or url format
- one can omit any part of connection string, e.g. user, host, etc.
- one can use multi-host strings, e.g. `postgresql://host1:123,host2:456/somedb`
- one can specify any custom connection parameter, e.g. `synchronous_commit`
- the host part may be either a host name or an IP address, e.g. `postgresql://[2001:db8::1234]/database`
- it's easier to store in the back-end and manipulate

# Cons
- users should know how to use it (not a valid reason, because pw3 is not a newbie thingy anyway)

# TODO
- [x] remove single connection options, e.g. host, post, etc.
- [x] add configuration kind type: url, file, folder
- [x] update config validation
- [x] update `GetPostgresDBConnection()`
- [x] update `main.go`
- [x] update `patroni.go`
- [x] update database schema
- [x] update UI
