### ISSUE TITLE
allow multiple parallel metric storages 

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch3#294]
As a user I want to have the ability to store metrics to several data stores simultaneously, e.g. 
- save to file for backup
- save to database for Grafana dashboards
- push to Prometheus for export

- [x] #295
- [x] add `MultiWriter` object
- [x] add `JSONWriter` object
- [x] add `PostgresWriter` object
- [x] #307
- [x] #309
- [x] switch prometheus to async mode
