### ISSUE TITLE
decouple `sources` into separate package

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch3#357]
- [x] add `sources` package with types
- [x] add Postgres config reader
- [x] add YAML config reader
- [x] move patroni discoverer from `main`
- [x] refactor sources obtaining in `main`
