### ISSUE TITLE
decouple `metrics` into separate package

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch3#372]
- [x] #373
- [x] #374
- [x] refactor `prometheus_*` YAML attributes
- [x] move postgres related code to metrics package
- [x] #401
- [x] update Docker images
- [x] #414
